import aboutImage from "../Assets/aboutImage.jpg";

const booksData = {
  "Grade 1": {
    Parisaraya: {
      title: "Parisaraya Book",
      grade: "Grade 1",
      subject: "Parisaraya",
      imageUrl: aboutImage,
      downloadLink: "parisaraya.pdf",
      readOnlineLink: "parisaraya-online",
    },
    Vidyawa: {
      title: "Vidyawa Book",
      grade: "Grade 1",
      subject: "Vidyawa",
      imageUrl: aboutImage,
      downloadLink: "vidyawa.pdf",
      readOnlineLink: "vidyawa-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 1",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    Ganithaya: {
      title: "Ganithaya Book",
      grade: "Grade 1",
      subject: "Ganithaya",
      imageUrl: aboutImage,
      downloadLink: "Ganithaya.pdf",
      readOnlineLink: "Ganithaya-online",
    },
    Demala: {
      title: "Demala Book",
      grade: "Grade 1",
      subject: "Demala",
      imageUrl: aboutImage,
      downloadLink: "Demala.pdf",
      readOnlineLink: "Demala-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 1",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 1",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 1",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 1",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
  },
  "Grade 2": {
    Parisaraya: {
      title: "Parisaraya Book",
      grade: "Grade 2",
      subject: "Parisaraya",
      imageUrl: aboutImage,
      downloadLink: "parisaraya.pdf",
      readOnlineLink: "parisaraya-online",
    },
    Vidyawa: {
      title: "Vidyawa Book",
      grade: "Grade 2",
      subject: "Vidyawa",
      imageUrl: aboutImage,
      downloadLink: "vidyawa.pdf",
      readOnlineLink: "vidyawa-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 2",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    Ganithaya: {
      title: "Ganithaya Book",
      grade: "Grade 2",
      subject: "Ganithaya",
      imageUrl: aboutImage,
      downloadLink: "Ganithaya.pdf",
      readOnlineLink: "Ganithaya-online",
    },
    Demala: {
      title: "Demala Book",
      grade: "Grade 2",
      subject: "Demala",
      imageUrl: aboutImage,
      downloadLink: "Demala.pdf",
      readOnlineLink: "Demala-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 2",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 2",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 2",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 2",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
  },
  "Grade 3": {
    Parisaraya: {
      title: "Parisaraya Book",
      grade: "Grade 3",
      subject: "Parisaraya",
      imageUrl: aboutImage,
      downloadLink: "parisaraya.pdf",
      readOnlineLink: "parisaraya-online",
    },
    Vidyawa: {
      title: "Vidyawa Book",
      grade: "Grade 3",
      subject: "Vidyawa",
      imageUrl: aboutImage,
      downloadLink: "vidyawa.pdf",
      readOnlineLink: "vidyawa-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 3",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    Ganithaya: {
      title: "Ganithaya Book",
      grade: "Grade 3",
      subject: "Ganithaya",
      imageUrl: aboutImage,
      downloadLink: "Ganithaya.pdf",
      readOnlineLink: "Ganithaya-online",
    },
    Demala: {
      title: "Demala Book",
      grade: "Grade 3",
      subject: "Demala",
      imageUrl: aboutImage,
      downloadLink: "Demala.pdf",
      readOnlineLink: "Demala-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 3",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 3",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 3",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 3",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
  },
  "Grade 4": {
    Parisaraya: {
      title: "Parisaraya Book",
      grade: "Grade 4",
      subject: "Parisaraya",
      imageUrl: aboutImage,
      downloadLink: "parisaraya.pdf",
      readOnlineLink: "parisaraya-online",
    },
    Vidyawa: {
      title: "Vidyawa Book",
      grade: "Grade 4",
      subject: "Vidyawa",
      imageUrl: aboutImage,
      downloadLink: "vidyawa.pdf",
      readOnlineLink: "vidyawa-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 4",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    Ganithaya: {
      title: "Ganithaya Book",
      grade: "Grade 4",
      subject: "Ganithaya",
      imageUrl: aboutImage,
      downloadLink: "Ganithaya.pdf",
      readOnlineLink: "Ganithaya-online",
    },
    Demala: {
      title: "Demala Book",
      grade: "Grade 4",
      subject: "Demala",
      imageUrl: aboutImage,
      downloadLink: "Demala.pdf",
      readOnlineLink: "Demala-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 4",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 4",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 4",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 4",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
  },
  "Grade 5": {
    Parisaraya: {
      title: "Parisaraya Book",
      grade: "Grade 5",
      subject: "Parisaraya",
      imageUrl: aboutImage,
      downloadLink: "parisaraya.pdf",
      readOnlineLink: "parisaraya-online",
    },
    Vidyawa: {
      title: "Vidyawa Book",
      grade: "Grade 5",
      subject: "Vidyawa",
      imageUrl: aboutImage,
      downloadLink: "vidyawa.pdf",
      readOnlineLink: "vidyawa-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 5",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    Ganithaya: {
      title: "Ganithaya Book",
      grade: "Grade 5",
      subject: "Ganithaya",
      imageUrl: aboutImage,
      downloadLink: "Ganithaya.pdf",
      readOnlineLink: "Ganithaya-online",
    },
    Demala: {
      title: "Demala Book",
      grade: "Grade 5",
      subject: "Demala",
      imageUrl: aboutImage,
      downloadLink: "Demala.pdf",
      readOnlineLink: "Demala-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 5",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 5",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 5",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 5",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
    //=============================================================================================================================================
  },
  "Grade 6": {
    Science: {
      title: "Science Book",
      grade: "Grade 6",
      subject: "Science",
      imageUrl: aboutImage,
      downloadLink: "science.pdf",
      readOnlineLink: "science-online",
    },
    Maths: {
      title: "Maths Book",
      grade: "Grade 6",
      subject: "Maths",
      imageUrl: aboutImage,
      downloadLink: "maths.pdf",
      readOnlineLink: "maths-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 6",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    History: {
      title: "History Book",
      grade: "Grade 6",
      subject: "History",
      imageUrl: aboutImage,
      downloadLink: "History.pdf",
      readOnlineLink: "History-online",
    },
    Civics: {
      title: "Civics Book",
      grade: "Grade 6",
      subject: "Civics",
      imageUrl: aboutImage,
      downloadLink: "Civics.pdf",
      readOnlineLink: "Civics-online",
    },
    Tamil: {
      title: "Tamil Book",
      grade: "Grade 6",
      subject: "Tamil",
      imageUrl: aboutImage,
      downloadLink: "Tamil.pdf",
      readOnlineLink: "Tamil-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 6",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 6",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 6",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 6",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    ICT: {
      title: "ICT Book",
      grade: "Grade 6",
      subject: "ICT",
      imageUrl: aboutImage,
      downloadLink: "ICT.pdf",
      readOnlineLink: "ICT-online",
    },
    Health: {
      title: "Health Book",
      grade: "Grade 6",
      subject: "Health",
      imageUrl: aboutImage,
      downloadLink: "Health.pdf",
      readOnlineLink: "Health-online",
    },
    PTS: {
      title: "PTS Book",
      grade: "Grade 6",
      subject: "PTS",
      imageUrl: aboutImage,
      downloadLink: "PTS.pdf",
      readOnlineLink: "PTS-online",
    },
    Geography: {
      title: "Geography Book",
      grade: "Grade 6",
      subject: "Geography",
      imageUrl: aboutImage,
      downloadLink: "Geography.pdf",
      readOnlineLink: "Geography-online",
    },
    // Add more books for grades
  },
  "Grade 7": {
    Science: {
      title: "Science Book",
      grade: "Grade 7",
      subject: "Science",
      imageUrl: aboutImage,
      downloadLink: "science.pdf",
      readOnlineLink: "science-online",
    },
    Maths: {
      title: "Maths Book",
      grade: "Grade 7",
      subject: "Maths",
      imageUrl: aboutImage,
      downloadLink: "maths.pdf",
      readOnlineLink: "maths-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 7",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    History: {
      title: "History Book",
      grade: "Grade 7",
      subject: "History",
      imageUrl: aboutImage,
      downloadLink: "History.pdf",
      readOnlineLink: "History-online",
    },
    Civics: {
      title: "Civics Book",
      grade: "Grade 7",
      subject: "Civics",
      imageUrl: aboutImage,
      downloadLink: "Civics.pdf",
      readOnlineLink: "Civics-online",
    },
    Tamil: {
      title: "Tamil Book",
      grade: "Grade 7",
      subject: "Tamil",
      imageUrl: aboutImage,
      downloadLink: "Tamil.pdf",
      readOnlineLink: "Tamil-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 7",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 7",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 7",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 7",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    ICT: {
      title: "ICT Book",
      grade: "Grade 7",
      subject: "ICT",
      imageUrl: aboutImage,
      downloadLink: "ICT.pdf",
      readOnlineLink: "ICT-online",
    },
    Health: {
      title: "Health Book",
      grade: "Grade 7",
      subject: "Health",
      imageUrl: aboutImage,
      downloadLink: "Health.pdf",
      readOnlineLink: "Health-online",
    },
    PTS: {
      title: "PTS Book",
      grade: "Grade 7",
      subject: "PTS",
      imageUrl: aboutImage,
      downloadLink: "PTS.pdf",
      readOnlineLink: "PTS-online",
    },
    Geography: {
      title: "Geography Book",
      grade: "Grade 7",
      subject: "Geography",
      imageUrl: aboutImage,
      downloadLink: "Geography.pdf",
      readOnlineLink: "Geography-online",
    },
    // Add more books for grades
  },
  "Grade 8": {
    Science: {
      title: "Science Book",
      grade: "Grade 8",
      subject: "Science",
      imageUrl: aboutImage,
      downloadLink: "science.pdf",
      readOnlineLink: "science-online",
    },
    Maths: {
      title: "Maths Book",
      grade: "Grade 8",
      subject: "Maths",
      imageUrl: aboutImage,
      downloadLink: "maths.pdf",
      readOnlineLink: "maths-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 8",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    History: {
      title: "History Book",
      grade: "Grade 8",
      subject: "History",
      imageUrl: aboutImage,
      downloadLink: "History.pdf",
      readOnlineLink: "History-online",
    },
    Civics: {
      title: "Civics Book",
      grade: "Grade 8",
      subject: "Civics",
      imageUrl: aboutImage,
      downloadLink: "Civics.pdf",
      readOnlineLink: "Civics-online",
    },
    Tamil: {
      title: "Tamil Book",
      grade: "Grade 8",
      subject: "Tamil",
      imageUrl: aboutImage,
      downloadLink: "Tamil.pdf",
      readOnlineLink: "Tamil-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 8",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 8",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 8",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 8",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    ICT: {
      title: "ICT Book",
      grade: "Grade 8",
      subject: "ICT",
      imageUrl: aboutImage,
      downloadLink: "ICT.pdf",
      readOnlineLink: "ICT-online",
    },
    Health: {
      title: "Health Book",
      grade: "Grade 8",
      subject: "Health",
      imageUrl: aboutImage,
      downloadLink: "Health.pdf",
      readOnlineLink: "Health-online",
    },
    PTS: {
      title: "PTS Book",
      grade: "Grade 8",
      subject: "PTS",
      imageUrl: aboutImage,
      downloadLink: "PTS.pdf",
      readOnlineLink: "PTS-online",
    },
    Geography: {
      title: "Geography Book",
      grade: "Grade 8",
      subject: "Geography",
      imageUrl: aboutImage,
      downloadLink: "Geography.pdf",
      readOnlineLink: "Geography-online",
    },
    // Add more books for grades
  },

  "Grade 9": {
    Science: {
      title: "Science Book",
      grade: "Grade 9",
      subject: "Science",
      imageUrl: aboutImage,
      downloadLink: "science.pdf",
      readOnlineLink: "science-online",
    },
    Maths: {
      title: "Maths Book",
      grade: "Grade 9",
      subject: "Maths",
      imageUrl: aboutImage,
      downloadLink: "maths.pdf",
      readOnlineLink: "maths-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 9",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    History: {
      title: "History Book",
      grade: "Grade 9",
      subject: "History",
      imageUrl: aboutImage,
      downloadLink: "History.pdf",
      readOnlineLink: "History-online",
    },
    Civics: {
      title: "Civics Book",
      grade: "Grade 9",
      subject: "Civics",
      imageUrl: aboutImage,
      downloadLink: "Civics.pdf",
      readOnlineLink: "Civics-online",
    },
    Tamil: {
      title: "Tamil Book",
      grade: "Grade 9",
      subject: "Tamil",
      imageUrl: aboutImage,
      downloadLink: "Tamil.pdf",
      readOnlineLink: "Tamil-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 9",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 9",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 9",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 9",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    ICT: {
      title: "ICT Book",
      grade: "Grade 9",
      subject: "ICT",
      imageUrl: aboutImage,
      downloadLink: "ICT.pdf",
      readOnlineLink: "ICT-online",
    },
    Health: {
      title: "Health Book",
      grade: "Grade 9",
      subject: "Health",
      imageUrl: aboutImage,
      downloadLink: "Health.pdf",
      readOnlineLink: "Health-online",
    },
    PTS: {
      title: "PTS Book",
      grade: "Grade 9",
      subject: "PTS",
      imageUrl: aboutImage,
      downloadLink: "PTS.pdf",
      readOnlineLink: "PTS-online",
    },
    Geography: {
      title: "Geography Book",
      grade: "Grade 9",
      subject: "Geography",
      imageUrl: aboutImage,
      downloadLink: "Geography.pdf",
      readOnlineLink: "Geography-online",
    },
  },
  "Grade 10": {
    Science: {
      title: "Science Book",
      grade: "Grade 10",
      subject: "Science",
      imageUrl: aboutImage,
      downloadLink: "science.pdf",
      readOnlineLink: "science-online",
    },
    Maths: {
      title: "Maths Book",
      grade: "Grade 10",
      subject: "Maths",
      imageUrl: aboutImage,
      downloadLink: "maths.pdf",
      readOnlineLink: "maths-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 10",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    History: {
      title: "History Book",
      grade: "Grade 10",
      subject: "History",
      imageUrl: aboutImage,
      downloadLink: "History.pdf",
      readOnlineLink: "History-online",
    },
    Civics: {
      title: "Civics Book",
      grade: "Grade 10",
      subject: "Civics",
      imageUrl: aboutImage,
      downloadLink: "Civics.pdf",
      readOnlineLink: "Civics-online",
    },
    Tamil: {
      title: "Tamil Book",
      grade: "Grade 10",
      subject: "Tamil",
      imageUrl: aboutImage,
      downloadLink: "Tamil.pdf",
      readOnlineLink: "Tamil-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 10",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 10",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 10",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 10",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    ICT: {
      title: "ICT Book",
      grade: "Grade 10",
      subject: "ICT",
      imageUrl: aboutImage,
      downloadLink: "ICT.pdf",
      readOnlineLink: "ICT-online",
    },
    Health: {
      title: "Health Book",
      grade: "Grade 10",
      subject: "Health",
      imageUrl: aboutImage,
      downloadLink: "Health.pdf",
      readOnlineLink: "Health-online",
    },
    PTS: {
      title: "PTS Book",
      grade: "Grade 10",
      subject: "PTS",
      imageUrl: aboutImage,
      downloadLink: "PTS.pdf",
      readOnlineLink: "PTS-online",
    },
    Geography: {
      title: "Geography Book",
      grade: "Grade 10",
      subject: "Geography",
      imageUrl: aboutImage,
      downloadLink: "Geography.pdf",
      readOnlineLink: "Geography-online",
    },
    English_Literature: {
      title: "English Literature Book",
      grade: "Grade 10",
      subject: "English Literature",
      imageUrl: aboutImage,
      downloadLink: "English Literature.pdf",
      readOnlineLink: "English Literature-online",
    },
    Sinhala_Literature: {
      title: "Sinhala_Literature Book",
      grade: "Grade 10",
      subject: "Sinhala_Literature",
      imageUrl: aboutImage,
      downloadLink: "Sinhala_Literature.pdf",
      readOnlineLink: "Sinhala_Literature-online",
    },
    // Add more books for grades
  },
  "Grade 11": {
    Science: {
      title: "Science Book",
      grade: "Grade 11",
      subject: "Science",
      imageUrl: aboutImage,
      downloadLink: "science.pdf",
      readOnlineLink: "science-online",
    },
    Maths: {
      title: "Maths Book",
      grade: "Grade 11",
      subject: "Maths",
      imageUrl: aboutImage,
      downloadLink: "maths.pdf",
      readOnlineLink: "maths-online",
    },
    English: {
      title: "English Book",
      grade: "Grade 11",
      subject: "English",
      imageUrl: aboutImage,
      downloadLink: "English.pdf",
      readOnlineLink: "English-online",
    },
    History: {
      title: "History Book",
      grade: "Grade 11",
      subject: "History",
      imageUrl: aboutImage,
      downloadLink: "History.pdf",
      readOnlineLink: "History-online",
    },
    Civics: {
      title: "Civics Book",
      grade: "Grade 11",
      subject: "Civics",
      imageUrl: aboutImage,
      downloadLink: "Civics.pdf",
      readOnlineLink: "Civics-online",
    },
    Tamil: {
      title: "Tamil Book",
      grade: "Grade 11",
      subject: "Tamil",
      imageUrl: aboutImage,
      downloadLink: "Tamil.pdf",
      readOnlineLink: "Tamil-online",
    },
    Dancing: {
      title: "Dancing Book",
      grade: "Grade 11",
      subject: "Dancing",
      imageUrl: aboutImage,
      downloadLink: "Dancing.pdf",
      readOnlineLink: "Dancing-online",
    },
    Art: {
      title: "Art Book",
      grade: "Grade 11",
      subject: "Art",
      imageUrl: aboutImage,
      downloadLink: "Art.pdf",
      readOnlineLink: "Art-online",
    },
    Music: {
      title: "Music Book",
      grade: "Grade 11",
      subject: "Music",
      imageUrl: aboutImage,
      downloadLink: "Music.pdf",
      readOnlineLink: "Music-online",
    },
    Sinhala: {
      title: "Sinhala Book",
      grade: "Grade 11",
      subject: "Sinhala",
      imageUrl: aboutImage,
      downloadLink: "Sinhala.pdf",
      readOnlineLink: "Sinhala-online",
    },
    ICT: {
      title: "ICT Book",
      grade: "Grade 11",
      subject: "ICT",
      imageUrl: aboutImage,
      downloadLink: "ICT.pdf",
      readOnlineLink: "ICT-online",
    },
    Health: {
      title: "Health Book",
      grade: "Grade 11",
      subject: "Health",
      imageUrl: aboutImage,
      downloadLink: "Health.pdf",
      readOnlineLink: "Health-online",
    },
    PTS: {
      title: "PTS Book",
      grade: "Grade 11",
      subject: "PTS",
      imageUrl: aboutImage,
      downloadLink: "PTS.pdf",
      readOnlineLink: "PTS-online",
    },
    Geography: {
      title: "Geography Book",
      grade: "Grade 11",
      subject: "Geography",
      imageUrl: aboutImage,
      downloadLink: "Geography.pdf",
      readOnlineLink: "Geography-online",
    },
    English_Literature: {
      title: "English Literature Book",
      grade: "Grade 11",
      subject: "English Literature",
      imageUrl: aboutImage,
      downloadLink: "English Literature.pdf",
      readOnlineLink: "English Literature-online",
    },
    Sinhala_Literature: {
      title: "Sinhala Literature Book",
      grade: "Grade 11",
      subject: "Sinhala Literature",
      imageUrl: aboutImage,
      downloadLink: "Sinhala Literature.pdf",
      readOnlineLink: "Sinhala Literature-online",
    },
    // Add more books for grades
  },
  // Add books for other grades
};

export default booksData;
